// const proxy = "https://cors-anywhere.herokuapp.com/"
// const url = "https://www.w3.org/Style/CSS/all-properties.en.json"
// fetch(proxy + url)
// .then(response => response.json())
// .then(json => {
//   const specifications = [...new Set(json.map(p => p.title))].sort()
// })
// .catch(error => console.log({error}))

export const specifications = [
  "CSS Animations Level 1",
  "CSS Backgrounds and Borders Module Level 3",
  "CSS Basic User Interface Module Level 3 (CSS3 UI)",
  "CSS Basic User Interface Module Level 4",
  "CSS Box Alignment Module Level 3",
  "CSS Cascading and Inheritance Level 3",
  "CSS Cascading and Inheritance Level 4",
  "CSS Color Module Level 3",
  "CSS Color Module Level 4",
  "CSS Containment Module Level 1",
  "CSS Custom Properties for Cascading Variables Module Level 1",
  "CSS Display Module Level 3",
  "CSS Exclusions Module Level 1",
  "CSS Fill and Stroke Module Level 3",
  "CSS Flexible Box Layout Module Level 1",
  "CSS Fonts Module Level 3",
  "CSS Fonts Module Level 4",
  "CSS Fragmentation Module Level 3",
  "CSS Generated Content Module Level 3",
  "CSS Generated Content for Paged Media Module",
  "CSS Grid Layout Module Level 1",
  "CSS Image Values and Replaced Content Module Level 3",
  "CSS Image Values and Replaced Content Module Level 4",
  "CSS Inline Layout Module Level 3",
  "CSS Intrinsic & Extrinsic Sizing Module Level 3",
  "CSS Line Grid Module Level 1",
  "CSS Lists and Counters Module Level 3",
  "CSS Logical Properties and Values Level 1",
  "CSS Masking Module Level 1",
  "CSS Multi-column Layout Module Level 1",
  "CSS Overflow Module Level 3",
  "CSS Overflow Module Level 4",
  "CSS Page Floats",
  "CSS Paged Media Module Level 3",
  "CSS Positioned Layout Module Level 3",
  "CSS Presentation Levels Module",
  "CSS Regions Module Level 1",
  "CSS Rhythmic Sizing",
  "CSS Round Display Level 1",
  "CSS Ruby Layout Module Level 1",
  "CSS Scroll Snap Module Level 1",
  "CSS Shapes Module Level 1",
  "CSS Speech Module",
  "CSS Table Module Level 3",
  "CSS Template Layout Module",
  "CSS Text Decoration Module Level 3",
  "CSS Text Decoration Module Level 4",
  "CSS Text Module Level 3",
  "CSS Text Module Level 4",
  "CSS Transforms Module Level 1",
  "CSS Transitions",
  "CSS Will Change Module Level 1",
  "CSS Writing Modes Level 3",
  "CSS Writing Modes Level 4",
  "CSS basic box model",
  "CSSOM View Module",
  "CSS 2.1",
  "Compositing and Blending Level 1",
  "Filter Effects Module Level 1",
  "Motion Path Module Level 1",
  "SVG Markers",
  "SVG Strokes"
]

export const supportedSpecifications = [
  "CSS 2.1",
  "CSS Animations Level 1",
  "CSS Backgrounds and Borders Module Level 3",
  "CSS Basic User Interface Module Level 3 (CSS3 UI)",
  "CSS Box Alignment Module Level 3",
  "CSS Color Module Level 3",
  "CSS Flexible Box Layout Module Level 1",
  "CSS Grid Layout Module Level 1",
  "CSS Image Values and Replaced Content Module Level 3",
  "CSS Masking Module Level 1",
  "CSS Multi-column Layout Module Level 1",
  "CSS Overflow Module Level 3",
  "CSS Shapes Module Level 1",
  "CSS Text Decoration Module Level 3",
  "CSS Text Module Level 3",
  "CSS Transforms Module Level 1",
  "CSS Transitions",
  "CSS Will Change Module Level 1",
  "CSS Writing Modes Level 3",
  "CSS Writing Modes Level 4",
  "CSS basic box model",
]

export default supportedSpecifications
